language: node_js
node_js:
- 4
- 5
- 6
notifications:
  email: false
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/117063f9c1031b17e557
    on_start: never
    on_failure: change
deploy:
  provider: npm
  email: hello@mylisabox.com
  api_key:
    secure: TODO
  on:
    tags: true
    repo: mylisabox/lisa-plugins-manager
    node: 6
